### ISSUE TITLE
Handle nils

### ISSUE THREAD

**Issue by brndnstks** [jadekler/eq_wo_order#2]
The following should work:

```
describe 'hello' do
  it 'world' do
    actual = ['foo']
    expected = nil

    expect(actual).not_to eq_wo_order expected
  end
end
```

Instead, I get:

> NoMethodError: undefined method `find_all' for nil:NilClass
> ./spec/features/super_real_spec.rb:8:in`block (2 levels) in <top (required)>'
> -e:1:in `load'
> -e:1:in`<main>'

**Comment by jeanbza** [comment]
Thanks! I'm on it

**Comment by brndnstks** [comment]
:+1:

**Comment by jeanbza** [comment]
Finished as of commit 66b8d54ed3e490a79387a9d6f6197abe6bac7db5
